empleado/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departamento_app"

urlpatterns = [
    path('departamento-lista/', views.DepartamentoListView.as_view(),name='departamento_list'),
    path('new-departamento/', views.NewDepartamentoView.as_view(),name='nuevo_departamento'),
     
]

empleado/applications/empleados/urls.py
from django.urls import path
from django.contrib import admin
from . import views

# se usa para darle un name a este conjunto de urls
app_name = "empleado_app"


urlpatterns = [
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(), 
        name = 'empleados_all'
        ),
    path('listar-by-area/<name>/', 
         views.ListByAreaEmpleado.as_view(),
           name= 'empleados_area'
           ),
    path('listar-empleados-admin/', 
         views.ListaEmpleadosAdmin.as_view(),
           name= 'empleados_admin'
        ),       
    path('listar-by-trabajo/<job>/', views.ListByTrabajo.as_view()),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabiliadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(), 
        name = 'empleado_detail'
        ),
    path('add-empleado/',
          views.EmpleadoCreateView.as_view(),
            name = 'empleado_add'
        ),
    path('success/', views.SuccessView.as_view(), name= 'correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),  
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'), 
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.home.views import IndexView
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/templates/includes/header.html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Empleados</li>
      <li>
        <a href="{% url 'empleado_app:empleados_all' %}">Listar</a>
        <!-- <a href="{/listar-todo-empleados}">Listar</a> -->
            <!-- <a href="{% url 'empleado_app:empleados_all' %}"></a> -->
    </li>
      <li><a href="{% url 'departamento_app:departamento_list' %}">Departamentos</a></li>
      <li><a href="{% url 'empleado_app:empleados_admin' %}">Administrar</a></li>
      <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo Departamento</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Buscar empleado"></li>
      <li><a href="{% url 'empleado_app:empleado_add' %}" class="button">Registrar Nuevo</a></li>
    </ul>
  </div>
</div>

<!-- app_name = "empleado_app"
  path('listar-todo-empleados/', views.ListAllEmpleados.as_view(), name = 'empleados_all'), -->