empleado/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departamento_app"

urlpatterns = [
    path('departamento-lista/', views.DepartamentoListView.as_view(),name='departamento_list'),
    path('new-departamento/', views.NewDepartamentoView.as_view(),name='nuevo_departamento'),
     
]

empleado/applications/empleados/urls.py
from django.urls import path
from django.contrib import admin
from . import views

# se usa para darle un name a este conjunto de urls
app_name = "empleado_app"


urlpatterns = [
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(), 
        name = 'empleados_all'
        ),
    path('listar-by-area/<name>/', 
         views.ListByAreaEmpleado.as_view(),
           name= 'empleados_area'
           ),
    path('listar-empleados-admin/', 
         views.ListaEmpleadosAdmin.as_view(),
           name= 'empleados_admin'
        ),       
    path('listar-by-trabajo/<job>/', views.ListByTrabajo.as_view()),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabiliadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(), 
        name = 'empleado_detail'
        ),
    path('add-empleado/',
          views.EmpleadoCreateView.as_view(),
            name = 'empleado_add'
        ),
    path('success/', views.SuccessView.as_view(), name= 'correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),  
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'), 
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.home.views import IndexView
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre',max_length=50)
    shor_name = models.CharField('Nombre Corto',max_length= 20, unique=True)
    #campo para saber si el departamento está activo o no
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Mi Departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['-name']
        unique_together = ('name','shor_name')

    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.shor_name
    

empleado/applications/departamento/forms.py
#Requerimiento es registrar un nuevo departamento, pero con un empleado a cargo.

from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField( max_length=50)
    apellido = forms.CharField( max_length=50)
    departamento = forms.CharField( max_length=50)
    shorname = forms.CharField( max_length=20)

empleado/applications/departamento/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import FormView

from .forms import NewDepartamentoForm

#tenemos que importar el modelo empleado para poder interceptar los datos
from applications.empleados.models import Empleado
from .models import Departamento


class DepartamentoListView(ListView):
    template_name = "departamento/lista.html"
    model = Departamento
    context_object_name = 'departamentos'
    


class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        print('Estamos en el form_valid')
        # como departamento es una clave foranea muchos a muchos, se necesita crear una instancia para poder
        # hacer el registro
        depa = Departamento(
            name=form.cleaned_data['departamento'],
            shor_name=form.cleaned_data['shorname']
        )
        depa.save()# aqui ya se guarda en la base de datos

        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellido']
        #para hacer un registro de empleado se usa el orm de django
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job = '1',
            departamento = depa
        )
        return super(NewDepartamentoView,self).form_valid(form)

empleado/templates/departamento/lista.html
{% extends 'base.html' %}


{% block title %}
    Lista departamentos
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamento in departamentos %}
                        <tr>
                            <td>{{departamento.name}}</td>
                            <td>{{departamento.shor_name}}</td>
                            <td>
                                <a class="button warging" href="{% url 'empleado_app:empleados_area' departamento.name %}">Ver empleados</a>
                            </td>
                        </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>

            </div>
        </div>
    </div>


{% endblock content %}
     
    

empleado/templates/departamento/new_departamento.html
{% extends 'base.html' %}

{% block title %}
    Registrar Departamento
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Registrar nuevo departamento</h1>
             <form class="cell callout grid-x grid-margin-x" method="post">{% csrf_token %}
                <div class="medium-6 cell">
                    <label>Nombre:
                      {{form.nombre}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Apellido:
                      {{form.apellido}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Departamento:
                      {{form.departamento}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Nombres:
                      {{form.shorname}}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <button type="submit" class="button">Guardar</button>
                </div>

             </form>

        </div>
    </div>
{% endblock content %}
    