empleado/applications/empleados/urls.py
from django.urls import path
from django.contrib import admin
from . import views

# se usa para darle un name a este conjunto de urls
app_name = "empleado_app"


urlpatterns = [
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(), 
        name = 'empleados_all'
        ),
    path('listar-by-area/<name>/', 
         views.ListByAreaEmpleado.as_view(),
           name= 'empleados_area'
           ),
    path('listar-empleados-admin/', 
         views.ListaEmpleadosAdmin.as_view(),
           name= 'empleados_admin'
        ),       
    path('listar-by-trabajo/<job>/', views.ListByTrabajo.as_view()),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabiliadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(), 
        name = 'empleado_detail'
        ),
    path('add-empleado/',
          views.EmpleadoCreateView.as_view(),
            name = 'empleado_add'
        ),
    path('success/', views.SuccessView.as_view(), name= 'correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),  
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'), 
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.home.views import IndexView
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/applications/empleados/models.py
from django.db import models
#para hacer la conexión con la tabla departamento se debe hacer la importación
from ckeditor.fields import RichTextField
from applications.departamento.models import Departamento

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades empleado'

    def __str__(self):
        return str(self.id) + '-' + self.habilidad 

# Create your models here.
class Empleado(models.Model):
    """ Modelo para tabla empleado """
    JOB_CHOICES = (
        ('0','CONTADOR'),
        ('1','ADMINISTRADOR'),
        ('2','ECONOMISTA'),
        ('3','INGENIERO'),
        ('4','OTRO'),
    )

    first_name = models.CharField('Nombres',max_length=60)
    last_name = models.CharField('apellidos',max_length=60)
    job = models.CharField('Trabajo', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null = True)
    #para relación muchos a muchos m2m
    full_name = models.CharField(
        'Nombre completos',
        max_length= 120,
        blank= True
    )
    habilidades = models.ManyToManyField(Habilidades)# una habilidad le pertenece a un empleado, y un empleado puede tener muchas habilidades
    #hoja_vida = RichTextField()
   
    class Meta:
        verbose_name = 'Mi Empleado'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['-first_name','last_name']
        unique_together = ('first_name','departamento')

    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name

empleado/applications/empleados/forms.py
from django import forms
from .models import Empleado 

class EmpleadoForm(forms.ModelForm):
    

    class Meta:
        model = Empleado     
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

empleado/applications/empleados/views.py
from typing import Any, Dict
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
    
from .models import Empleado
from .forms import EmpleadoForm

#Requerimientos
# 1 Lista todos los empleados de la empresa
# 2 Listar todos los empleados que pertenecen a un area de la empresa
# 3 Listar empleados por trabajo
# 4 listar los empleados por palabra clave
# 5 listar las habilidades de un empleado


# 1 Lista todos los empleados de la empresa
class  ListAllEmpleados(ListView):
    template_name = 'empleados/list_all.html'
    #Aquí hacemos paginacion
    paginate_by = 4
    ordering = 'first_name'

    def get_queryset(self):
        print('***********')
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            full_name__icontains = palabra_clave
        )
        print('lista resultado: ',lista)
        return lista


class  ListaEmpleadosAdmin(ListView):
    template_name = 'empleados/lista_empleados.html'
    #Aquí hacemos paginacion
    paginate_by = 10
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado

           



    # model = Empleado
    # context_object_name = 'lista_albert'

    # queryset = Empleado.objects.filter(...)
    # for empleado in queryset:
    #     print(empleado)
    #     print(empleado.firts_name)

   
    

# 2 Listar todos los empleados que pertenecen a un area de la empresa

#forma 1
# class ListByAreaEmpleado(ListView):
#      """ Lista empleados de un area """
#      template_name = 'empleados/list_by_area.html'
#      queryset = Empleado.objects.filter(
#          departamento__name = 'TESTER'
#      )

# forma 2
class ListByAreaEmpleado(ListView):
     """ Lista empleados de un area """
     template_name = 'empleados/list_by_area.html'
     context_object_name = 'empleados'
    
     def get_queryset(self):
        area = self.kwargs['name']
        lista = Empleado.objects.filter(
         departamento__name = area
        )
        return lista   
     
# 4 listar los empleados por palabra clave

class ListEmpleadosByKword(ListView):
    """ lista de empleados por palabra clave """
    template_name = 'empleados/by_kword.html'
    context_object_name = 'empleadus'

    def get_queryset(self):
        print('***********')
        palabra_clave = self.request.GET.get("kword",'')
        lista = Empleado.objects.filter(
            first_name = palabra_clave
        )
        print('lista resultado: ',lista)
        return lista

# 5 listar las habilidades de un empleado

class ListHabiliadesEmpleado(ListView):
    template_name = 'empleados/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(id=12)
        print(empleado.habilidades.all())
        return empleado.habilidades.all()


# 3 Listar empleados por trabajo: por revisarrrrrr

class ListByTrabajo(ListView):
    """ Lista empleados por trabajo """
    template_name ='empleados/list_by_trabajo.html'
    def get_queryset(self):
        trabajo = self.kwargs['job']
        lista = Empleado.objects.filter(
            job = trabajo
        )  
        return lista
    
   # ---------------A parti de aquí DetalView---------------------

class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = 'empleados/detail_empleado.html'
   
    def get_context_data(self, **kwargs):
         context = super(EmpleadoDetailView,self).get_context_data(**kwargs)
         context['titulo'] = 'empleado del mes'
         return context 


#---------------- a partir de aquí vista CreateView-----------------------

class EmpleadoCreateView(CreateView):
    template_name = 'empleados/add.html'
    model = Empleado
    form_class = EmpleadoForm
    # forma 1 de traer todos los campos del modelo empleado
    #fields = ['first_name','last_name','job', 'departamento','habilidades', 'avatar',]
    #forma2
    #fields = ('__all__')
    # URL donde se va a redireccionar una vez completado el proceso. Se recargue la misma pagina.
    success_url= reverse_lazy('empleado_app:empleado_add')

    def form_valid(self, form) :
        #logica del proceso
        empleado = form.save(commit=False)# se recupera una instancia del formulario pero con una instancia a la base de datos
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        #luego se hace la actualización a la base de datos de ese full_name
        empleado.save()
        print('variable empleado posee')
        print(empleado)
        return super(EmpleadoCreateView,self).form_valid(form)


#--------- para redireccionar a otra pagina-----------------------
class SuccessView(TemplateView):
    template_name = "empleados/success.html"

#--------------para realizar actualizaciones con UpdateView-----------------Empleado

class EmpleadoUpdateView(UpdateView):
    template_name = "empleados/update.html"
    model = Empleado
    fields = ['first_name','last_name','job', 'departamento','habilidades']
      # URL donde se va a redireccionar una vez completado el proceso. Se recargue la misma pagina.
    success_url= reverse_lazy('empleado_app:empleados_admin')

    def post(self, request,*args, **kwargs):
        self.object = self.get_object()
        print('*****************METODO POST*************')
        print('*****************************************')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request,*args,**kwargs)


    def form_valid(self, form) :
       print('*********METODO FORM VALID************')
       print('*****************************************')
       return super(EmpleadoUpdateView,self).form_valid(form)


#-------------------------Para eliminar DeleteView--------------------------------
class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "empleados/delete.html"
    success_url= reverse_lazy('empleado_app:empleados_admin')

empleado/templates/empleados/add.html
{% extends 'base.html' %}


{% block title %}
  Registrar empleado
{% endblock title %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x">
      <h1 class="cell"> Registrar empleado</h1>
      <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data" > {% csrf_token %}
          <div class="medium-6 cell">
            <label>Nombres:
              {{form.first_name}}
            </label>
          </div>
          <div class="medium-6 cell">
            <label>Apellidos:
              {{form.last_name}}
            </label>
          </div>
          <div class="medium-6 cell">
            <label>Trabajo:
              {{form.job}}
            </label>
          </div>
          <div class="medium-6 cell">
            <label>Departamento:
              {{form.departamento}}
            </label>
          </div>
          <div class="medium-6 cell">
            <label>Habilidades:
              {{form.habilidades}}
            </label>
          </div>
          <div class="medium-6 cell">
            <label>Foto:
              {{form.avatar}}
            </label>
          </div>
          <div class="medium-6 cell">
              <button type= "submit"  class="button success">Guardar</button>  
          </div>

      </form>
  </div>
</div>


  
{% endblock content %}
  
  
  

empleado/templates/empleados/by_kword.html
<h1>Buscar empleados por palabra clave</h1>
<form method="GET">{% csrf_token %}
    <input type = "text" id ="kword" name ="kword" placeholder=" Ingrese nombre aquí ">
    <button type="submit">Buscar</button>
</form>

<h3>Lista Resultados</h3>
<ul>
    {% for e in empleadus %}
        <li>{{e}}</li>
    {% endfor %}    
</ul>

empleado/templates/empleados/delete.html
{% extends 'base.html' %}
{% block <title> %}
    Eliminar Empleado
{% endblock <title> %}

 
 {% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell"> Eliminar empleado: {{ object.first_name }} </h1>
            <form  class ="cell" method="POST">{% csrf_token %}
                <div class="callout secondary">
                    <h5>¿ Desea eliminar este empleado ?</h5>
                    <button type="submit" class="alert button">Confirmar</button>
                </div>
            </form>

        </div>
    </div>
 {% endblock content %}
       
    

empleado/templates/empleados/detail_empleado.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{object.full_name}}
{% endblock title %}
    

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x grid-margin align-center">
            <div class="cell large-4 card" style="width: 300px; margin-top: 10px;">
                <div class="card-divider">
                  {{empleado.get_job_display}}
                </div>

                
                {% if empleado.avatar %}
                    <img src="{{empleado.avatar.url}}">
                {% else %}
                    <img src="{% static 'img/reunion.jpg' %}">
                {% endif %}
                    
                
                <div class="card-section">
                  <h4>{{empleado.full_name}}</h4>
                  <p>{{empleado.last_name}}</p>
                  <p>{{empleado.departamento.shor_name}}</p>
                  <p><span class="label">Habilidades:</span></p>
                  <ul class="vertical menu">
                    
                    {% for h in empleado.habilidades.all  %}
                       <li> {{h.habilidad}} </li> 
                    {% endfor %}
                        
                  </ul>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}
    

<h1> Detalle de un  empleado </h1>

{{ object}}

<h3> Todos los datos del modelo: </h3>
<p>{{empleado.first_name}}</p>
<p>{{empleado.last_name}}</p>
<p>{{empleado.departamento}}</p>
<p>{{empleado.habilidades}}</p>

empleado/templates/empleados/habilidades.html
<h1>Habilidades empleado</h1>

<ul>
    {% for h in habilidades %}
        <li>{{ h }}</li>
    {% endfor %}
</ul> 

empleado/templates/empleados/list_all.html
{% extends 'base.html' %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="Buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in object_list %}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td><a class="button warning" href="{% url 'empleado_app:empleado_detail' e.id %}">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">

                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                    {% endif %}


                    {% for pagina in paginator.page_range %}

                    {% if pagina == page_obj.number  %}
                    <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>
                    {% else %}
                    <li class=""><a href="?page={{pagina}}">{{pagina}}</a></li>
                    {% endif %}
                    {% endfor %}


                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>
                    {% endif %}




                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

empleado/templates/empleados/list_by_area.html
{% extends 'base.html' %}


{% block title %}
    <h1>Lista de empleados por departamento</h1>
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell"> Empleados por area:</div>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="200">ID</th>
                            <th>NOMBRES</th>
                            <th width="150">APELLIDOS</th>
                            <th width="150">DEPARTAMENTO</th>
                            <th width="150">ACCION</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados %}
                        <tr>
                            <td>{{e.id}}</td>
                            <td>{{e.first_name}}</td>
                            <td>{{e.last_name}}</td>
                            <td>{{e.departamento}}</td>
                            <td><a class="button warning" href="{% url 'empleado_app:empleado_detail' e.id %}">Ver</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>
{% endblock content %}



<h1>Listar empleados por departamentos</h1>

<ul>
    {% for empleado in object_list %}
        <li>{{ empleado.nombre }}</li>
    {% endfor %}
</ul> 

empleado/templates/empleados/list_by_trabajo.html
<h1>Listar empleados por trabajos</h1>
<!-- {{object_list}}  -->
{{object_list}}

 <!-- <ul>
    {% for e in object_list %}
        <li>{{e}}</li>
    {% endfor %}
 </ul>  -->

empleado/templates/empleados/lista_empleados.html
{% extends 'base.html' %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
       
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in object_list %}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td><a class="button success" href="{% url 'empleado_app:modificar_empleado' e.id %}">Editar</a></td>
                        <td><a class="button alert" href="{% url 'empleado_app:eliminar_empleado' e.id %}">Eliminar</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">

                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                    {% endif %}


                    {% for pagina in paginator.page_range %}

                    {% if pagina == page_obj.number  %}
                    <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>
                    {% else %}
                    <li class=""><a href="?page={{pagina}}">{{pagina}}</a></li>
                    {% endif %}
                    {% endfor %}


                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>
                    {% endif %}




                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

empleado/templates/empleados/success.html
<h1>Felicitaciones, se guardo correctamente el empleado</h1>

empleado/templates/empleados/update.html
{% extends 'base.html' %}


{% block title %}
    Editar empleado
{% endblock title %}
   

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar Empleado
        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST"> {% csrf_token %}
                
                <div class="cell large-6">
                    <label>Nombres
                        {{form.first_name}}
                    </label>
                </div>
                
                <div class="cell large-6">
                    <label>Apellidos:
                        {{form.last_name}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo:
                        {{form.job}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Area:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades:
                        {{form.habilidades}}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="submit success button">Guardar</button>
                </div>
                
               
            </form>

        </div>

    </div>

</div>

{% endblock content %}

    



<h1>Actualización del empleado</h1>